project:
    team_id: 9
    release_title: D4loc
aquaint:
    aquaint1_directory: /dropbox/17-18/573/AQUAINT
    aquaint2_directory: /dropbox/17-18/573/AQUAINT-2

    aquaint_doc_dir: 
    aquaint_topic_index: /dropbox/17-18/573/Data/Documents/devtest/GuidedSumm10_test_topics.xml

output:
    summary_dir: outputs/D4loc
    #results_dir: outputs/results   (jgreve: not supposed to be child of outputs)
    results_dir: results/loc
    max_words: 100

noqrmatrix:
sentence_location:
    article_weight_file: outputs/position_data/SummaryOrderByArticle-20180528-134057.csv
    sentence_weight_file: outputs/position_data/SummaryOrderBySentence-20180528-134057.csv
