project:
    team_id: 9
    release_title: Naruto++

aquaint:
    aquaint1_directory: src/aquaint_test1
    aquaint2_directory: src/aquaint_test2

    aquaint_doc_dir: 
    aquaint_topic_index: src/GuidedSumm10_test_topics.xml

# jgreve: added 5/31 to support rouge.sh, haven't test run this *.yml
rouge:
    modeldata_dir: /dropbox/17-18/573/Data/models/devtest

output:
    summary_dir: outputs/D2
    results_dir: results
    max_words: 100
