project:
    team_id: 9
    release_title: Naruto++

aquaint:
    aquaint1_directory: aquaint_test1
    aquaint2_directory: aquaint_test2

    aquaint_doc_dir: 
    aquaint_topic_index: GuidedSumm10_test_topics.xml

output:
    summary_dir: outputs/D2
    results_dir: results
    max_words: 100

qrmatrix:
# sentence_location:
