project:
    team_id: 9
    release_title: Naruto++

aquaint:
    aquaint1_directory: aquaint_test1
    aquaint2_directory: aquaint_test2

    aquaint_doc_dir:
    aquaint_topic_index: GuidedSumm10_test_topics.xml

output:
    summary_dir: output/D2
    results_dir: output/results
    max_words: 100

# Test configuration to read one article file only
# one_config:
#    article_file: aquaint_test1/nyt/1999/19990330_NYT