project:
    team_id: 9
    release_title: Naruto++

aquaint:
    aquaint1_directory: /opt/dropbox/17-18/573/AQUAINT
    aquaint2_directory: /opt/dropbox/17-18/573/AQUAINT-2

    aquaint_doc_dir: /opt/dropbox/17-18/573/Data/Documents/training/2009
    aquaint_topic_index: UpdateSumm09_test_topics.xml

output:
    summary_dir: outputs/D2
    results_dir: results
    max_words: 100

# Test configuration to read one article file only
# one_config:
#    article_file: aquaint_test1/nyt/1999/19990330_NYT
